### ISSUE TITLE
Nouveau favicon

### ISSUE THREAD

**Issue by real34** [Paris-Web/pw-design-system#18]
Pour ne pas oublier. Mais pas d’urgence à mon avis.

**Comment by padawan** [comment]
Je n'ai pas programmé de logique dans MT ni dans le header, il faut remplacer sur le disque les deux fichiers suivants :
favicon.ico et favicon.png (à la racine : /srv/sites/www/www).

**Comment by JulienPradet** [comment]
Bon, du coup j'ai regardé un peu plus en détail, et il me faudrait des trucs en plus @joachimesque stp (j'aurais pu le faire sur ma tour, mais je n'ai aucun logiciel graphique sur mon pc portable).

Quand j'upload le SVG sur le site fourni par Nicolas (qui a l'air super d'ailleurs) j'ai plusieurs problèmes :
* les images générées ont un truc bizarre au niveau du P
* je me dis que ça peut être pas mal de forcer la couleur blanche pour lettres PW
* pour Windows, ca vaut peut être le coup d'utiliser la version blanche ?

Qu'en penses-tu ?

**Comment by nico3333fr** [comment]
Oui, autant utiliser une version avec un fond blanc, ça évitera des rendus hasardeux.

**Comment by joachimesque** [comment]
Voilà les packages :)

[favicon_bleue.zip](https://github.com/Paris-Web/pw-design-system/files/1951393/favicon_bleue.zip)
[favicon_rose.zip](https://github.com/Paris-Web/pw-design-system/files/1951399/favicon_rose.zip)

Je verrais bien la rose pour le site et la bleue pour l'inscription.

```
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#058fd6">
<meta name="msapplication-TileColor" content="#2b5797">
<meta name="theme-color" content="#ffffff">
```

**Comment by JulienPradet** [comment]
Adjugé vendu ! Je m'occupe de mettre tout ça en place.

@nico3333fr  dès que tout sera un peu plus stabilisé, j'attaquerai la partie PWA/offline ;)
Notamment pour avoir accès au programme en hors ligne avec de joulis Service Workers et pouvoir faire sa sélection de confs. Ca sera la partie cool !
Mais je pense que ce sera plutôt vers fin août. Il y a d'autres trucs qu'on avait mis en standby/simplifiés par rapport à la maquette de @joachimesque qu'il serait bien mettre en place. Je pense notamment à l'affichage du programme et à la page des archives.
Pfiou, c'est loin d'être fini ! :P

**Comment by nico3333fr** [comment]
@JulienPradet oui, y a pas d'urgence, et même une implé basique pourra toujours aider quand le wifi sautera durant l'événement. 😄 

J'avais fait ça à la rache sur Van11y, et c'est déjà pas si mal : https://van11y.net/layout/js/van11yjs.js et https://van11y.net/service-worker.js 😁

**Comment by JulienPradet** [comment]
J'ai mis à jour les fichiers qu'il faut sur MT.

Par contre, je n'ai pas su comment republier les blogs (j'ai bien le bouton, mais la modification dans le Head HTML ne s'est pas propagée). Du coup il n'y a que les pages de Paris Web qui ont le nouveau favicon.

@padawan, notre sauveur ?

**Comment by padawan** [comment]
C'est vos droits que j'ai limité un peu trop sur MT (c'est sensible cette bestiole). Je vais republier. Il faut d'abord que j'applique le nouveau thème sur tous les blogs programme.

**Comment by JulienPradet** [comment]
Merci :)
