### ISSUE TITLE
Accessibilité du burger sur mobile

### ISSUE THREAD

**Issue by nico3333fr** [Paris-Web/pw-design-system#25]
Yop,

j'ai remarqué que si on tabule au clavier sur l'affichage mobile (ou quand on zoome fort), quand on ouvre le burger, si on continue de tabuler, ça continue sur la page en arrière-plan une fois qu'on devrait boucler dans le menu.

Je sais pas si ça peut aider, si jamais, j'avais fait ça sur un de mes scripts : https://github.com/nico3333fr/van11y-accessible-modal-tooltip-aria/blob/master/src/van11y-accessible-modal-tooltip-aria.es6.js#L361 (grosso modo, ça écoute les tabulations quand le menu est ouvert, et ça capture le focus dans le menu ouvert.

Ce n'est pas prioritaire si jamais (et si besoin est je le fixerai moi-même plus tard).

**Comment by nico3333fr** [comment]
@JulienPradet pour le piège clavier, c'est top 👍 

Par contre, le "Esc" ne marche pas pour moi, c'est normal ?

**Comment by JulienPradet** [comment]
Ah oui. Je l'avais fait, mais j'ai du le recasser. Je corrige ça !

**Comment by JulienPradet** [comment]
Ca devrait être bon maintenant @nico3333fr  !
N'hésite pas à réouvrir l'issue si tu vois que ce n'est pas bon.

**Comment by nico3333fr** [comment]
ça roule, parfait :)
