### ISSUE TITLE
Page Programme : liste de thèmes trop grande

### ISSUE THREAD

**Issue by joachimesque** [Paris-Web/pw-design-system#41]
Pour éviter ça : 
![image](https://user-images.githubusercontent.com/1781070/39099636-4a59ec20-467e-11e8-8341-69aef1f9ba41.png)

Je prévois une situation de bloc à révéler/cacher. Je maquette ça dès que possible. Si vous avez des recommandations je prends.

**Comment by JulienPradet** [comment]
Est-ce qu'on peut fermer ici du coup ?

**Comment by joachimesque** [comment]
Oui
