### ISSUE TITLE
Améliorer la sélection du menu

### ISSUE THREAD

**Issue by JulienPradet** [Paris-Web/pw-design-system#48]
Sur iphone, j'ai remarqué que la navigation du menu se fait mal. Le hover s'active au lieu de rediriger vers le lien en question.

N'ayant pas d'iphone sous la main, si quelqu'un peut s'en occuper, ça serait chouette.

**Comment by padawan** [comment]
J'ai un iPhone mais pas les compétences pour corriger ce bug. En fait il faut taper deux fois, la première active l'hover, la seconde lui coupe le poil et suit le lien.

**Comment by joachimesque** [comment]
J'ai testé sur Safari et Firefox (mais les deux ont le même moteur?), je n'ai pas vu ce comportement. Un clic, ça charge la page.

**Comment by padawan** [comment]
C'est sur Safari Mobile sur iOS, pas Safari sur macOS (pas le même navigateur).

**Comment by joachimesque** [comment]
Oui, bon, j'ai pas précisé de contexte, je suis sous iOS (iPhone 5S, iOS 11.3), sur Safari Mobile je n'ai pas ce problème (je viens de revérifier ce matin). J'installe 11.3.1 et je regarde s'il y a un problème.

**Comment by padawan** [comment]
Pardon, quand tu as précisé Firefox j'ai cru que tu parlais d'un ordi. J'ai ce problème sur un iPhone 8+ avec Safari sur iOS 11.3. Voici une copie du menu quand je suis sur la page Orateurs et que je tape une fois sur Programme : 

![img_0397](https://user-images.githubusercontent.com/91673/39236280-ab6198aa-4878-11e8-8b26-84389432f0e0.PNG)

Il faut que je tape une seconde fois pour que ça suive le lien.

**Comment by JulienPradet** [comment]
Ah oui, bien vu !
Je vais faire une branche pour corriger ça en utilisant [`@media (pointer: fine)`](
https://css-tricks.com/annoying-mobile-double-tap-link-issue/).
Est-ce que vous pourrez vérifier que ça fonctionne bien ?

Il faudrait aussi vérifier le clic sur les portraits (quand on clique sur l'image de l'orateur). Il y a le même mécanisme de hover, mais a priori, je ne pense pas que ça devrait impacter la navigation.

**Comment by JulienPradet** [comment]
C'est déployé ici : https://stage.paris-web.fr/design-system/bugfix-double-tap-ios/

**Comment by joachimesque** [comment]
Ça marche chez moi !

À tester sur iPhone 8+ :)

**Comment by padawan** [comment]
Dites les enfants, je commence à être totalement largué sur le report des multiples petites modifications ici dans MT. Il faut trouver un process ou un moyen pour garder les deux synchrones (et j'avoue que je n'ai pas de solution miracle, à part suggérer que quand vous mettez le repo à jour, vous pensez à mettre MT à jour ou à me guider sur exactement quoi changer dans le HTML/CSS).

**Comment by padawan** [comment]
Faites gaffe aussi au fait que le design-system est sur www ET stage, et qu'ils ne sont probablement pas synchrones non plus tous les deux (il faut virer stage).

**Comment by JulienPradet** [comment]
@padawan De manière générale, si je ferme une issue ici, c'est que je l'ai mise sur MT.
Pour les trucs que je ne sais pas faire, je t'assigne l'issue pour terminer l'intégration dans MT.
Est-ce que ça te va comme fonctionnement ?

J'ai viré la majeure partie du Design System sur stage. (Certains liens que j'ai mis ici datent d'avant la mise en place du design system sur la prod, c'est pour ça qu'il y a des éléments pas clairs.)

Je vais chercher des gens avec les bons téléphones/pc pour tester pour nous. :)

**Comment by padawan** [comment]
C'est parfait, ça me va très bien !

**Comment by JulienPradet** [comment]
C'est publié sur le site. J'attends juste une confirmation pour les utilisateurs de terminaux hybrides (PC + tactile par exemple).
