### ISSUE TITLE
[CI] Déplacer le Design System sur www.paris-web.fr

### ISSUE THREAD

**Issue by JulienPradet** [Paris-Web/pw-design-system#49]
Afin de faciliter la communication à terme sur le Design System,
Il faudrait mettre à disposition le design system directement sur https://www.paris-web.fr/design-system/master/

Aujourd'hui c'est déjà le cas, mais il faudrait modifier la CI pour le mettre sur la prod plutôt que sur staging.

**Comment by padawan** [comment]
Bonne idée. Si on pousse la logique jusqu'au bout il faut aussi rendre ce dépôt public.

**Comment by joachimesque** [comment]
Il l'est depuis hier, pour faciliter les bug reports :)

**Comment by JulienPradet** [comment]
@padawan Ma branche est prête pour le mettre en place. (https://github.com/Paris-Web/pw-design-system/tree/feature/switch-to-public-design-system)
Par contre, le dossier existant est en root sur le serveur. Est-ce que tu pourrais remettre les permissions stp ?

@real34 Je crois que tu avais une commande magique pour supprimer les branches qui n'étaient plus sur git. Est-ce que tu pourrais me la donner stp ? Je pense que ca ne ferait pas de mal au serveur que de faire tourner un cron toutes les nuits pour nettoyer les branches inutiles

**Comment by padawan** [comment]
Désolé, gag classique quand je copie un truc et que j'oublie de rectifier. Le dossier /srv/sites/www/www/design-system appartient désormais à "sites", tu devrais pouvoir le modifier.

**Comment by real34** [comment]
Je n’ai encore jamais pris le temps de la faire cette commande magique… c’est un bon gros `rm -fr .......` fait à la main avec un diff _a bisto de nas_.

Je viens de faire un petit ménage manuel mais laisse ouvert le ticket pour prendre un jour le temps de faire cette commande.
