### ISSUE TITLE
Menu : élément "spécial"

### ISSUE THREAD

**Issue by joachimesque** [Paris-Web/pw-design-system#50]
Sur l'ancien site, certains éléments du menu étaient mis en exergue selon le moment de l'année. Avant l'événement, c'était "Inscription", pendant l'événement c'est "Direct".

Je propose la même chose ici, avec l'élément mis en exergue en rose `brand-01` (avec le hover en `brand-01-dark`).

<img src="https://user-images.githubusercontent.com/1781070/39202690-f38e1ecc-47f2-11e8-9432-4c47e1c57518.png" height="500">

**Comment by padawan** [comment]
Je n'aime pas trop le mélange menu/CTA. Le bouton CTA "Inscrivez-vous" est sur l'image Hero (c'est ce bouton qui était mis en avant, la confusion venant du fait qu'il était placé dans la barre de navigation de l'ancien site. Ou alors il faut un traitement graphique réellement différent du hover du menu (là je trouve que c'est un peu confus, il faudrait voir en pratique avec le survol).

**Comment by JulienPradet** [comment]
Je vous ferai une branche qui montre ce que ça donne d'ici demain.

**Comment by joachimesque** [comment]
OK je vais regarder les nuances de couleurs de brand-01-dark… il est plus saturé mais pas tant que ça, je vais l'assombrir aussi.

**Comment by joachimesque** [comment]
Je propose cette nouvelle couleur :
![image](https://user-images.githubusercontent.com/1781070/39357939-a47d03ba-4a14-11e8-912d-2b8dc88051b5.png)

`--brand-01-dark: #b40b57;`
