### ISSUE TITLE
Home : élément "citations"

### ISSUE THREAD

**Issue by joachimesque** [Paris-Web/pw-design-system#51]
On va pouvoir ajouter [l'élément "citations"](https://stage.paris-web.fr/design-system/master/modules/quote/) sur la home, avec les citations ci-dessous.

J'ai eu quelques votes sur les citations sélectionnées, d'après ces votes il y a cette sélection. Je ne pense pas recevoir plus de votes. Bien sûr c'est pas trop tard, n'hésitez pas dire si l'une ou l'autre des citations sélectionnées sont de trop.

Si il y a des citations trop longues il faudrait peut-être voir à diminuer la taille à `font-size: 1.33rem;` sur ces citations spécifiques.

---
## 3

> Paris Web, c’est un évènement fondé sur la volonté d’échanger entre les différents acteurs du web. Organisés par des véritables passionnés, c’est l’occasion d’apporter un nouveau regard sur les métiers du web. Pour certains, c’est aussi le moyen de véhiculer des valeurs qui leur sont chères, tels que l’accessibilité des outils digitaux pour tous, les standards ouverts…

> Lucie Noël, Yateo, [PARIS WEB 2017 : notre experte UX/UI vous raconte les ateliers.](https://www.yateo.com/blog/paris-web-notre-experte-vous-raconte)

---
## 4

> Paris Web c’est une des plus importantes, et surtout des plus anciennes, conférences francophones autour du web, de l’accessibilité et de la qualité. Ce sont les maîtres-mots de cet événement et comme tous les ans ils sont très bien mis en lumière.

> [Compte-rendu de Paris Web 2017 - Le blog de Clever Age](https://blog.clever-age.com/fr/2017/10/20/compte-rendu-de-paris-web-2017/)

---
## 7 

> Pendant trois jours tout ce petit monde tour à tour observateur et acteur explore, développe, analyse et projette ses expériences aux autres. On vient écouter et échanger autour de sujets techniques, de design et d’accessibilité.

> L‘équipe LunaWeb - [Paris Web 2017 - Back to the future](http://blog.lunaweb.fr/paris-web-2017/)

---
## 9

> It’s such a great conference. The people are passionate and respectful –no, they are caring and it makes the conference extra special. The staff is dedicated and wonderful. The speakers are excellent. It’s probably the most inclusive conference

> Coralie Mercier, [#ParisWeb 2016: notes and thoughts (day 1)](https://coraliemercier.wordpress.com/2016/10/03/paris-web-2016-notes-and-thoughts-day1/)

---
## 11

>  Paris Web te rappelle une chose fondamentale : c'est beau d'avoir des valeurs communes et l'amitié avec. Célébrons nos compétences ! 

> Xavier Mouton-Dubosc, [Souvenirs de Paris Web 2016](https://dascritch.net/post/2016/10/04/Souvenirs-de-Paris-Web-2016)

---
## 14

> Paris web c’est une belle organisation qui croit en l’égalité des chances. L’accessibilité pour tous, que la différence soit visible ou non, sans jugement, là ou d’autres font ou cherchent la différence. Le staff de Paris Web, malgré le changement de cette édition, reste fidèle à ses valeurs, et ça fait plaisir. Les profils de Paris web sont nombreux, ce sont les acteurs du web dans sa globalité. Une communauté faite de gens normaux, avec des valeurs et des faiblesses, qui se réunissent dans un but précis : échanger autour du web et de ses bonnes pratiques.

> Laurie Amiot, [Paris web et L'se réalisent : interlude parisien](https://webcreatrice.com/interlude-parisien/)

---
## 15

> Nous avons passés 2 jours à apprendre, et échan­ger autour de nos métiers. Cette expé­rience qui nous permet une fois de plus de tour­ner notre métier vers l’ave­nir, d’in­ter­ro­ger notre respon­sa­bi­lité de profes­sion­nels du Web sur des ques­tions comme la vie privée, l’im­pact envi­ron­ne­men­tal, la collecte des datas, et le bien être de l’uti­li­sa­teur.

> Aymeric Dussauze et Morgane Delacroix, [Vous saurez TOUT sur Paris Web 2016](https://digitalpingpong.com/news/vous-saurez-tout-sur-paris-web-2016)

---
## 20

> Paris Web est un événement pas tout a fait comme les autres. Au-delà des bisounours, des licornes et des arc-en-ciels, c’est un événement pour les professionnels du web par les professionnels du web dans une esprit bon enfant de partage – constructif et émotionnel. 

> Acti, [Paris web 2015 : On y était](https://www.acti.fr/blog/paris-web-2015-on-y-etait/)

---
## 23

> Des conférences de qualité, sur la forme comme sur le fond.    
> Paris Web n’est pas une conférence technique, on y parle de tout et ce n’est pas pour acquérir de nouvelles compétences techniques que nous y allons, mais pour la communauté, l’ouverture d’esprit et la fraîcheur apportée sur notre métier au quotidien.

> JoliCode, [Paris Web 2015 fête ses 10 ans !](https://jolicode.com/blog/paris-web-2015-fete-ses-10-ans)

---

**Comment by JulienPradet** [comment]
Je ne saurai pas vraiment intégrer le module en étant efficace sur MT (l'histoire des include random etc.), même si j'imagine pouvoir m'inspirer du module des orateurs si jamais François n'est pas dispo.
Est-ce que tu pourras t'en occuper @padawan stp ?

**Comment by padawan** [comment]
Oui bien sûr, je prends.

**Comment by JulienPradet** [comment]
Ca m'a l'air en place. On ferme ?

**Comment by joachimesque** [comment]
ok pour moi
