### ISSUE TITLE
Refaire la page "Direct"

### ISSUE THREAD

**Issue by JulienPradet** [Paris-Web/pw-design-system#53]
Backport de l'issue Jira : [SITE-639](https://jira.paris-web.fr/browse/SITE-639)

Il faut faire la page qui sera affichée pendant la conférence, puis faire la page qui permet de revoir les lives.
http://direct.paris-web.fr/

Note de françois :
> C'est géré à la main chaque année, parce que la techno utilisée par le prestataire (Veodem p. ex.) change à chaque fois. C'est du bricolage ad hoc.

Mais ça peut être l'occasion de faire du bricolage un poil plus sympathique.

**Comment by joachimesque** [comment]
OK je vais regarder ça :)

**Comment by joachimesque** [comment]
https://zpl.io/bo9Xy5W

![live](https://user-images.githubusercontent.com/1781070/45286408-1013a200-b4e6-11e8-9268-0c13ee2b2166.png)

@JulienPradet j'ai gardé le design très simple (le lien vers le site est un bouton "fantôme", mais si tu penses qu'un lien "normal" est plus pertinent, n'hésite pas à remplacer). Je pense que le mieux est de faire une page HTML toute simple, histoire que @padawan puisse bricoler rapidement

**Comment by real34** [comment]
WIP : https://www.paris-web.fr/design-system/page-direct/pages/direct/

Je vous dit quand c’est terminé.

**Comment by joachimesque** [comment]
> Il manque un moyen visible de basculer d'une salle à l'autre (il y a deux flux en direct).

C'est vrai, j'y ai absolument pas pensé !

Après la `div.direct__video` je propose ça :

````HTML
<div class="direct__titre">
  <p>Vous regardez le flux <strong>Amphitorium Descarte</strong> <a href="#" class="btn btn-small">Voir le flux Amphitorium Pascal</a></p>
</div>
````

Si c'est pas trop tard, voilà la nouvelle version, avec les logos corrects (et exportables) : https://zpl.io/bo9Xy5W

**Comment by CarineR** [comment]
Amphitorium??? :')))

**Comment by real34** [comment]
C’est joli amphitorium je trouve !

J’ai mis à jour le design system en fonction.
Merci pour les retours.
