### ISSUE TITLE
Espace sur le layout à deux colonnes ?

### ISSUE THREAD

**Issue by JulienPradet** [Paris-Web/pw-design-system#55]
Jira SITE-635 par Carine
> La largeur de la colonne de droite pour les actus et l'espacement par rapport à la partie centrale ici est un peu limite : https://stage.paris-web.fr/actualites/2018/01/devenez-partenaires-de-paris-web-2018.php

**Comment by padawan** [comment]
N.B. ne vous basez pas sur stage pour ce genre de chose, il n'est pas DU TOUT à jour vu que j'ai cessé de travailler dessus la semaine dernière avant de basculer le nouveau design sur www.

**Comment by joachimesque** [comment]
Voilà la situation actuelle

![image](https://user-images.githubusercontent.com/1781070/39300329-9b3e796a-494b-11e8-86a3-f2f518ef1122.png)

Est-ce que pour mieux séparer ça vous dit une bordure à gauche du bloc de droite ? Un peu dans le même genre que les bordures qui séparent les blocs dans la page Sponsors.

Est-ce que la largeur du bloc de droite vous parait choquante ?

**Comment by CarineR** [comment]
C'est l'espace entre les deux colonnes centrale et de droite qui est un chouilla trop petit, surtout si tu le compares avec l'espace entre les colonnes de gauche et centrale. Quand je suis fatiguée, j'ai du mal à capter qu'il y a 2 blocs distincts et je dois faire un effort pour arrêter la lecture de la colonne centrale et passer à la ligne en dessous. Aujourd'hui c'est moins flagrant pour moi que le jour où j'avais reporté cette issue (ça fait 2-3 jours que j'ai fait de belles nuits de sommeil aussi, ça aide), ça tire juste un peu et j'arrive à passer outre. Y a plusieurs solutions envisageables. Peut-être que juste un peu d'espacement en plus entre la fin du texte de la colonne centrale et le début du texte de la colonne de droite serait suffisant.

**Comment by padawan** [comment]
Je mets ça où dans le CSS, dans le bloc ```@media screen and (min-width: 44em)``` après ```.content--2-cols .content__sidebar``` ?

**Comment by joachimesque** [comment]
il faut voir avec @JulienPradet je ne sais pas trop :)

**Comment by padawan** [comment]
J'ai essayé, ça a l'air de fonctionner : https://www.paris-web.fr/association/ et https://www.paris-web.fr/actualites/2018/03/prolongation-de-lappel-a-sujets-pour-paris-web-2018.php

**Comment by JulienPradet** [comment]
Ok, je mettrai ça dans le CSS du Design System.

**Comment by JulienPradet** [comment]
@joachimesque la modif a aussi un impact sur le module d'actualité de la page d'accueil :
https://www.paris-web.fr/

Est-ce qu'on la garde ?

**Comment by joachimesque** [comment]
Ça me parait pertinent, même si on n'en a pas tant besoin que ça
