### ISSUE TITLE
Supprimer les liens non utilisés sur la page Programme

### ISSUE THREAD

**Issue by JulienPradet** [Paris-Web/pw-design-system#56]
Jira SITE-646 Yann :
> Supprimer les liens "Accueil des participants", "Ouverture des conférences", "Changement de salle", "Pause" sur les pages programmes : https://stage.paris-web.fr/2018/04.php

Les liens sont désactivés via CSS aujourd'hui. Il faut faire la modif côté MT aussi.

**Comment by padawan** [comment]
C'était déjà fait sur le site depuis au moins hier ;-)
