### ISSUE TITLE
Améliorer le style des tableaux par défaut

### ISSUE THREAD

**Issue by JulienPradet** [Paris-Web/pw-design-system#58]
Sur le billet qui annonce le programme 2018, les tableaux ne sont pas très jolis et comme indiqué [par Carine](https://github.com/Paris-Web/pw-design-system/issues/55#issuecomment-384621209), ça gêne à la lecture.

Je peux reprendre vaguement le style du [tableau dans "Devenez Sponsor"](https://www.paris-web.fr/design-system/feature-sponsors-menu/pages/devenez-sponsor/) si ça vous va.

**Comment by CarineR** [comment]
OK pour moi. N'hésitez pas à modifier le contenu de l'article correspondant
dans MT pour lui ajouter des classes si c'est nécessaire. (Et pingue-moi
derrière que je reporte dans le wiki pour que ça soit repris dans les
actualités suivantes si jamais on refait des tableaux)

2018-04-26 14:31 GMT+02:00 Julien Pradet <notifications@github.com>:

**Comment by joachimesque** [comment]
OK ça me va
