### ISSUE TITLE
Style des listes de liens sidebar

### ISSUE THREAD

**Issue by joachimesque** [Paris-Web/pw-design-system#59]
Il faudra enlever le style de liste et le padding sur les listes de liens dans la sidebar.

```
.nav-sidebar ul {
    list-style: none;
    padding: 0;
}
```

**Comment by padawan** [comment]
Là je vais laisser les sorciers du CSS revoir ça et #55 parce que j'ai l'impression que j'ai collé ce dernier au mauvais endroit, et je ne sais pas où placer ça du coup.
