### ISSUE TITLE
Reprendre le markup de la page des membres

### ISSUE THREAD

**Issue by JulienPradet** [Paris-Web/pw-design-system#62]
Il faudrait retravailler le markup de la page des membres : https://www.paris-web.fr/association/membres.php

Est-ce qu'on affiche les gens avec les portraits simples ou les portraits longs ? https://www.paris-web.fr/design-system/master/components/portrait/
Je crois que @joachimesque  avait parlé de faire avec les portraits simples.

**Comment by joachimesque** [comment]
Je pensais à portraits longs pour le bureau, portraits façon l'actuelle liste d'orateurs mais avec une phrase de description dessous. Qu'en pensez-vous ?

**Comment by CarineR** [comment]
J'en pense que si on met des descriptions au bureau, on en met à tout le
monde. Photo+Nom+"label court / rôle"+comptes réseaux sociaux ou site
internet seraient largement suffisant

**Comment by joachimesque** [comment]
OK, alors on prend le modèle Portrait Long pour tous les membres actuels, et Portrait Réduit (avec phrase dessous) pour les anciens membres ?

**Comment by CarineR** [comment]
OK pour les portraits courts sur les anciens, cela permettra de conserver
les liens, mais ça sera moins mis en avant.

Ensuite pour les membres actuels : soit portrait simple, soit portrait
long. Il faut juste que ça soit pareil pour tous les membres de l'équipe.

2018-04-27 12:07 GMT+02:00 Joachim <notifications@github.com>:

**Comment by joachimesque** [comment]
Portrait Long ça me va, il y aura moins à retravailler par chaque membre de l'équipe :)

**Comment by nico3333fr** [comment]
Serait-il possible de mettre à jour cette page tant que vous y êtes ? ;)

**Comment by joachimesque** [comment]
https://jira.paris-web.fr/browse/SITE-656

**Comment by JulienPradet** [comment]
Je n'ai pas réussi à me connecter au jira ce matin, donc je réponds ici : 
https://www.paris-web.fr/design-system/feature-membres/pages/membres/

Est-ce que ça vous va comme résultat ?
A noter que j'ai du coup agrandi la taille des pages sur deux colonnes. Sinon, dans la partie autre, on n'arrivait à mettre que deux portraits par ligne. Ca impacte aussi les pages d'actu : https://www.paris-web.fr/design-system/feature-membres/pages/actualite/
cc  @joachimesque

**Comment by joachimesque** [comment]
Ça me parait nickel ! En revanche il y a beaucoup de Christophe Porteneuve dans ta liste, et je m'appelle désormais https://www.paris-web.fr/img/staff/joachim-robert.jpg :)

Je ne vois pas de problème avec la page Actus modifiée, tout me parait très bien. Merci !

**Comment by JulienPradet** [comment]
Oops, désolé ! Je vais repasser sur tous les noms / images :p

**Comment by real34** [comment]
Sauf mention contraire je mergerai ça demain et mettrai à jour le markup dans MT.

**Comment by nico3333fr** [comment]
C'est super ! 👍
