### ISSUE TITLE
Améliorer le contraste des tags au focus (et au hover aussi tiens)

### ISSUE THREAD

**Issue by nico3333fr** [Paris-Web/pw-design-system#65]
Salut,

sur https://www.paris-web.fr/2018/ quand on se balade au clavier, le focus est très satisfaisant, sauf sur les tags (devops, etc.) : là on ne sait pas trop où on est quand on passe dessus.

@joachimesque une suggestion ?

Faites suivre à @padawan quand c'est fixé (enfin, si c'est pas automatique, j'ai pas encore tout compris)

Bises,
Nico

**Comment by joachimesque** [comment]
En fait, il faudrait que le statut actif soit le même que le statut hover.

**Comment by JulienPradet** [comment]
Je pense que vous ne parlez pas des mêmes tags. Je vais mettre en place ce que tu as dit @joachimesque , mais j'ai l'impression que @nico3333fr  parle surtout des tags au sein même d'une présentation, pas de la liste des filtres au dessus.

Je pense à deux solutions :
* soit on fait en sorte que le hover soit rose, à l'image de ce qu'on a fait pour les liens
* soit on rajoute une bordure blanche à l'image de ce qui est fait sur la page d'accueil sur le "Inscrivez vous" (mais ça risque d'être petit)

**Comment by JulienPradet** [comment]
Up @nico3333fr

**Comment by nico3333fr** [comment]
Vi, je parlais bien des tags au sein même d'une présentation, pas de la liste des filtres au dessus. @real34

**Comment by nico3333fr** [comment]
C'est top, encore ;)
