### ISSUE TITLE
JS qui ajoute un style inutile dans Partenaires

### ISSUE THREAD

**Issue by nico3333fr** [Paris-Web/pw-design-system#66]
Hello la team site,

sur la page https://www.paris-web.fr/partenaires.php le logo de Delicious Insights en-dessous de "Sponsors Platine" a un truc bizarre :  la source est ainsi :
```html
<img src="/partenaires/2018/delicious-insights.svg" alt="Delicious Insights" width="166" height="220">
```
et dans le DOM, y a un inutile attribut style qui s'ajoute :
```html
<img src="/partenaires/2018/delicious-insights.svg" alt="Delicious Insights" style="height: 213px;" width="166" height="220">
``` 

Y a quoi dans le JS pour que ceci s'ajoute ? (après vérif avec François, ça ne vient pas de MT)

Bises,
Nico

**Comment by JulienPradet** [comment]
En effet, ça vient du JS.

En gros, c'était très compliqué (impossible ?) de faire en sorte d'aligner les logos avec juste du CSS pour les sponsors qui ne sont pas platine. Les problèmes rencontrés étaient : le logo qui devient trop grand par rapport à sa taille initiale, parfois deux logos d'une même ligne qui sont trop petits en hauteur et donc un "trou" dans la page, etc. Une solution envisageable aurait été d'utiliser les CSS grid, mais à l'époque je n'avais pas encore essayé.

Du coup j'ai fait un bout de JS qui calcule la taille et la position des logos pour qu'ils soient à la bonne taille en fonction du niveau de sponsor et des logos qui sont à côté. Cela dit, je n'avais pas prévu le cas d'un SVG dont la viewbox serait petite. D'où votre souci initial. La solution de rajouter les attributs width et height est la bonne.

**Comment by real34** [comment]
J’imagine que tout est bon, je ne vois pas quel était le problème visuellement mais désormais j’ai l’impression que « ça passe ».

Je clos l’issue et comme toujours : manifestez-vous sans scrupules si je me fourvoyais !
