### ISSUE TITLE
Bug sur la recherche

### ISSUE THREAD

**Issue by nico3333fr** [Paris-Web/pw-design-system#67]
Hello tous,

je viens de voir un bug assez désagréable sur l'affichage du programme : 
Sur https://www.paris-web.fr/2018/recherche/accessibilit%C3%A9 survolez "Tout", "jeudi 04/10", etc. ça fait un décalage assez pénible.

Bizarre, car la page https://www.paris-web.fr/2018/ n'est pas impactée. (?)

Merci de fixer ça à l'occase ;)

**Comment by padawan** [comment]
C'est réglé. Visiblement le UL de navigation entre tout et les calendriers a obligatoirement besoin qu'un des LI soit activé, sinon sa hauteur augmente dès l'apparition du soulignement. Solution : activer "Tout" dans les résultats de recherche (le filtre par thème n'agit que sur la totalité du programme, pas dans les calendriers).

**Comment by nico3333fr** [comment]
You rock 👍
