### ISSUE TITLE
Page 404

### ISSUE THREAD

**Issue by joachimesque** [Paris-Web/pw-design-system#69]
Pour les pages 404, je propose ce visuel :
![image](https://user-images.githubusercontent.com/1781070/42312598-0108620c-8041-11e8-83cb-3f00e18340f0.png)

Le texte est à définir, je propose :

> Oups…
> La page que vous recherchez n’existe pas,
> ou n’est plus accessible à l’adresse demandée.

En taille H2, centrée :
![image](https://user-images.githubusercontent.com/1781070/42312935-cebf4788-8041-11e8-8508-143a9bf7aa1b.png)

Voilà le fichier source (SVG) de l'illustration.
[404.svg.zip](https://github.com/Paris-Web/pw-design-system/files/2165763/404.svg.zip)

**Comment by padawan** [comment]
(Pardon, je réalise que c'est pour intégrer au DS, je suis en avance de phase sur le CMS)

**Comment by joachimesque** [comment]
De but en blanc je dirais, ajoute une balise `style="width:100%;"` à la section qui englobe l'illustration et le lien…

```
<section style="text-align:center">
    <img src="https://www.paris-web.fr/img/404.svg" style="width:100%;">
    <p>
        <a href="/" class="btn">Revenir à l'accueil</a>
    </p>
</section>
```
C'est pas la méthode la plus élégante mais ça marche pas mal :)

Et comme tu as vu je rajoute aussi un `style="width:100%;"` sur l'image, parce que ça rend mieux avec le texte ferré à gauche (oui on ne centre pas tout le texte courant, c'est illisible)

**Comment by JulienPradet** [comment]
@joachimesque Est-ce que ce rendu te conviendrait ?
https://www.paris-web.fr/design-system/404/pages/404/

J'ai laissé du coup la partie à propos des autres solutions qui me paraîssait pas mal, mais ce n'est pas forcément pertinent :man_shrugging: 

@padawan Je backporterai les modifs sur MT une fois que ce sera bon.
Par contre, le seul truc que je ne saurai pas faire dans l'immédiat, c'est d'enlever le fil d'ariane et le titre de la page. Tu pourrais me filer un coup de main là dessus ?

**Comment by joachimesque** [comment]
Toutafé ! On peut demander sur Slack/#site ce qu'ils en pensent, mais si ça vous convient ici, moi ça me convient :) Merci!

**Comment by padawan** [comment]
@JulienPradet est-ce que c'est vraiment gênant voire utile de le supprimer (en termes d'accessibilité, ça fournit un lien direct vers l'accueil) ?

(Pour être franc, c'est pas mal de boulot pour ajouter une exception dans les gabarits sur une page qui sera vue pendant deux secondes par trois péquins, le tout pour une raison qui me semble purement esthétique.)

**Comment by JulienPradet** [comment]
C'est mis en place en l'état du coup.
