### ISSUE TITLE
Illustrations erreurs 403/500

### ISSUE THREAD

**Issue by joachimesque** [Paris-Web/pw-design-system#71]
Voilà les licornes pour les erreurs 403 et 500. S'il est impossible de faire des pages spécifiques pour la page 500 c'est pas grave (en revanche 403 ça devrait être possible non ?)

[403.svg.zip](https://github.com/Paris-Web/pw-design-system/files/2253086/403.svg.zip)
[500.svg.zip](https://github.com/Paris-Web/pw-design-system/files/2253087/500.svg.zip)

**Comment by joachimesque** [comment]
Et si vous avez d'autres codes HTTP à illustrer, faites la liste :)

**Comment by padawan** [comment]
C'est en ligne :
- https://www.paris-web.fr/403.php
- https://www.paris-web.fr/500.php

Illustration en marche : https://www.paris-web.fr/staff/ (403, je n'ai pas, de tête, d'exemple pour déclencher une erreur 500).

**Comment by real34** [comment]
Je clos cette demande étant donné que cela semble avoir été géré avec brio ! :clap: 

Si besoin de nouveaux chef-d’œuvres on pourra la remettre en service :D
