### ISSUE TITLE
Évolutions du site pendant / après l'événement

### ISSUE THREAD

**Issue by joachimesque** [Paris-Web/pw-design-system#73]
Est-ce qu'on a prévu comment gérer la homepage pour le pendant et l'après événement ?

https://wiki.paris-web.fr/pages/viewpage.action?pageId=64127191

Je ne crois pas avoir poussé de maquettes sur Zeplin, certains points étaient à définir, notamment :

- Le module « suivre le direct » [HOME - Jeudi et Vendredi.jpg](https://wiki.paris-web.fr/display/design/Maquettes+site+2016?preview=/46891710/48070796/HOME%20-%20Jeudi%20et%20Vendredi.jpg)
- Un module « Mémo » avec un lien vers la page Memo (codes WiFi, programme, etc) ?
- Le module « Revivez l’événement » [HOME - Apres l'event.jpg](https://wiki.paris-web.fr/display/design/Maquettes+site+2016?preview=/46891710/48070794/HOME%20-%20Apres%20l%27event.jpg)
 - Le module « Paris Web en chiffres » ?

Où est la page du live ? Où est-ce que je peux regarder ce qu'on change ?

**Comment by joachimesque** [comment]
Module "Suivre en direct"
· https://zpl.io/bWLxAWn

**Comment by padawan** [comment]
Je le faisais en posant mes gros doigts directement via SFTP (voire vi, oui je suis un dinosaure :p) mais on va faire ceinture et brettelles avec MT dès fois qu'IBM ait bloqué le port 22 sur leur réseau.

**Comment by padawan** [comment]
L'ancienne page direct.paris-web.fr est ici : http://direct.paris-web.fr
La rapatrier dans le site/MT permettrait de ne pas avoir à tout se retaper (style, header/footer etc.).

**Comment by JulienPradet** [comment]
Voilà le HTML qu'il faudra ajouter pour mettre le module qu'avait proposé @joachimesque .
Cela viendrait remplacer toute la `<section>` qui contient le `kezako`.

Je ne sais pas quand est-ce que l'opération sera lancée, du coup je te laisserai faire @padawan. 

```html
<section class="direct-link">
    <main>
        <h2>Suivez le direct !</h2>
        <ul class="direct-link__list">
            <li><a class="btn" href="/direct/index.php">Amphithéâtre René Descartes</a></li>
            <li><a class="btn" href="/direct/pascal.php">Auditorium Blaise Pascal</a></li>
        </ul>
    </main>
    <aside>
        <p>
            Afin de coordonner l’activité bouillonnante sur les réseaux et pour que tout le monde puisse s’y retrouver, voici le tag à utiliser et à suivre :
            <strong class="h1-like">#ParisWeb</strong>
        </p>
    </aside>
</section>
```

**Comment by padawan** [comment]
Super, merci. Par contre j’ai dû reprendre les classes du kezako précédent parce que là c’est pas bon du tout en termes de marge (il n’y en a aucune).

**Comment by JulienPradet** [comment]
Oops, j'ai eu un souci de push.
C'est corrigé @padawan

**Comment by padawan** [comment]
Merci d’avoir corrigé sur le site :)
