### ISSUE TITLE
Page Programme > Tout : Pas de date sur les items filtrés

### ISSUE THREAD

**Issue by joachimesque** [Paris-Web/pw-design-system#79]
Le contenu est différent entre les listes non filtrées :

>    jeudi 09h20 
>    Conférence (50 mn)
>    Salle : Auditorium René Descartes

et les listes filtrées 

>    2018
>    Conférences
>    50 mn
>    Salle : Auditorium René Descartes

Est-ce que l'absence de date est motivée ?

Je pense qu'il faudrait le même template sur les deux listes, avec date, heure et année. Qu'en pensez-vous ?

(merci @nhoizey)

------

## Captures

Liste non filtrée

![image](https://user-images.githubusercontent.com/1781070/47155878-161b5080-d2e6-11e8-9180-bb456320e1ed.png)

Liste filtrée

![image](https://user-images.githubusercontent.com/1781070/47155927-3b0fc380-d2e6-11e8-84d8-0eec620df685.png)

**Comment by padawan** [comment]
Je vaisregarder ça, c’est généré par deux gabarits différent et j’ai dû oublier de reporter certains trucs sur celui de recherche (le 2e).
